server:
  port: 9531
  servlet:
    context-path: /ape-client

#auth-server: http://localhost:9526/ape-space

#security:
#  oauth2:
#    client:
#      client-id: ape
#      client-secret: ape
#      user-authorization-uri: ${auth-server}/oauth/authorize
#      access-token-uri: ${auth-server}/oauth/token
#    resource:
#      jwk:
#        key-set-uri: ${auth-server}/oauth/token_key
spring:
  application:
    name: client
    # redis配置
  redis:
    host: 47.115.125.76
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数
    timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    prefer-ip-address: true
