server:
  port: 9526
  servlet:
    context-path: /ape-user

spring:
  application:
    name: ape-user-service
  servlet:
    multipart:
      # 单个文件上传大小
      max-file-size: 1GB
      # 总上传文件大小
      max-request-size: 3GB
      enabled: true
  # 返回json的全局时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 数据库配置
  datasource:
    druid:
      web-stat-filter:
        enabled: false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(ENGsFSSwuWJfPkf+usCYDt/cZvq3gZBK8Dd79/505kd5qJbbsqmvj2XYV3zAdgYOLFEFZtC8HlkjeLCBMyyzvrd3hrc4Lp1BpuSVx/xa44CJ/+87ExC54GIXw9jtArDfzfCwEP/xowraks0WBg9KoSyAHvKEGk2erXb4s2xzVgUcknOaPKZdpeP52OKw/SQX)
    username: ENC(dzr/bA6xho4Uf6dRAFihn2oPy7Ef61JLMAg36LOPWswtpEG+GMUDwhFP+x4AFP6N)
    password: ENC(G30fX2QbG1uixh0/Tz+GRC1S8kbB9+gSGGW73dPn6XsDVmehkeiPrYWdBs+XSB6J)
  # redis配置
  redis:
    host: ENC(aOtY1Fk+CwQfXMOokhOnljjoovZN8F03FCHmeGcdk7F1In7GAYf5+VhHeT0p6Yud)
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数
    timeout: 5000

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ape.*.model
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    prefer-ip-address: true

# feign配置
feign:
  hystrix:
    enabled: true

#logging:
#  file:
#    path:
