server:
  port: 8001
#  servlet:
#    context-path: /ape-space

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka,http://${eureka.instance.hostname}:7002/eureka

spring:
  application:
    name: ape-gateway8001
  # redis配置
  redis:
    host: ENC(G4MK1HiE6+zgC/Rr34H+R6KT4J3pfpyTURRYEp5rLkJgoeP2iXPIVIsYCGdlQIXS)
    port: 6379
    password: ENC(BIYU1lwpTm2K2nxU498+Ob2QJIkgnAebFpegs6I5mzYaQZ5Km/mqCgTnA9TsbIxa)
    database: 0
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数
    timeout: 5000
  cloud:
    gateway:
      globalcors:
        # 全局允许跨域访问
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-originPatterns: "*"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        # 注意：lb://ape-user-server的服务名称不能和Path=/ape-user/**的请求路径前缀一致，不然报404
        - id: ape-article-router
          uri: lb://ape-article-service
          predicates:
            - Path=/ape-article/**
        - id: ape-user-router
          uri: lb://ape-user-service
          predicates:
            - Path=/ape-user/**
        - id: sms-router
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oss-router
          uri: lb://oss-service
          predicates:
            - Path=/oss/**
        - id: client
          uri: lb://client
          predicates:
            - Path=/ape-client/**
#          filters:
#            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9526/ape-user/rsa/publicKey' #配置RSA的公钥访问地址
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/ape-space/oauth/token"

