server:
  port: 9525
#  servlet:
#    context-path: /sms

spring:
  application:
    name: sms-service
  redis:
    host: ENC(aOtY1Fk+CwQfXMOokhOnljjoovZN8F03FCHmeGcdk7F1In7GAYf5+VhHeT0p6Yud)
    port: 6379
    password: ENC(n/0EmazbURtBPOkmeRxWX5wQqFm13bBY73jkydTMaNDW5AuQmDSjMHyAD8uMQVdq)
    database: 0
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数
    timeout: 5000
    servlet:
      multipart:
        max-file-size: 15MB

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka,http://${eureka.instance.hostname}:7002/eureka
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1

# feign配置
feign:
  hystrix:
    enabled: true

# 榛子云短信配置
zhenzi:
  sms:
    apiUri: https://sms_developer.zhenzikj.com
    appId: 104813
    appSecret: 80660e02-6d38-4889-b056-f31cddf45614
    expire: 12400000
    templateId: 3738
