server:
  port: 9536

spring:
  application:
    name: ape-oss

aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      bucketName: ape-space
      accesskeyId: LTAI5tFe7qNg8qWEzSaZYtJG
      accesskeySecret: n6cbsDaFFYoglh05rjP4qQw2xbEJPF

eureka:
  client:
    register-with-eureka: true    #表示是否将自己注册进eureka server，默认true
    #是否从eureka server抓取已有的注册信息，默认true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://106.52.169.191:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ape-oss
    #eureka服务端在收到最后一次心跳后等待时间上限，单位秒（默认90秒），超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
    #eureka客户端向服务端发送心跳的时间间隔，单位秒（默认30秒）
    #lease-renewal-interval-in-seconds: 1
#ribbon:
  # 指的是建立连接后从服务器读取到可用资源所用的时间
#  ReadTimeout: 5000
  # 指的是建立连接所用的时间，使用于网络正常的情况下，两端连接所用的时间
#  ConnectTimeout: 20000
feign:
  hystrix:
    enabled: true
